In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('data.csv')

In [9]:
df[(df['propertyType'] == 'Apartment') & (df['typeOfArea'] == 'Land')]

,area,floorRange,typeOfSale,price,propertyType,typeOfArea,mktSegment,Year,region
3,77.0,36-40,Sub Sale,1940000,Apartment,Strata,RCR,2024,Central
4,93.0,01-05,Resale,1500000,Apartment,Strata,RCR,2020,Central
5,40.0,06-10,Resale,930000,Apartment,Strata,RCR,2024,Central
10,81.0,31-35,Resale,2070000,Apartment,Strata,RCR,2024,Central
12,83.0,01-05,Resale,1600000,Apartment,Strata,RCR,2024,Central
...,...,...,...,...,...,...,...,...,...
3515,90.0,01-05,Resale,1270000,Apartment,Strata,OCR,2021,North-East
3517,119.0,01-05,Resale,1430000,Apartment,Strata,RCR,2019,East
3518,42.0,01-05,Resale,750000,Apartment,Strata,OCR,2023,North-East
3520,182.0,01-05,Resale,2080000,Apartment,Strata,RCR,2024,East
3537,76.0,01-05,Resale,1100000,Apartment,Strata,OCR,2023,East